export const AUTH_FAILED = 'AUTH_FAILED';
export const USER_EXIST = 'USER_EXIST';
export const PAYMENT_FAILED = 'PAYMENT_FAILED';
export const SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';

export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
