export const AUTH_FAILED = 'AUTH_FAILED';
export const PAYMENT_FAILED = 'PAYMENT_FAILED';
export const SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';

export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const USER_EXIST = 'USER_EXIST';
export const USER_NOT_EXIST = 'USER_NOT_EXIST';
export const VERIFY_CODE_INCORRECT = 'VERIFY_CODE_INCORRECT';
export const MONEY_NOT_ENOUGH = 'MONEY_NOT_ENOUGH';

export const FILE_NOT_EXIST = 'FILE_NOT_EXIST';
